Drop table if exists Trader cascade;
Create table Trader (Code VARCHAR(50),
                    Name VARCHAR2(50),
                    PRIMARY KEY(Code)) ;

Drop table if exists Orderr cascade;
Create table Orderr (Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    Ticker VARCHAR2(50),
                    Trader VARCHAR(50),
                    PRIMARY KEY(Id),
                    FOREIGN KEY (Trader) REFERENCES Trader(Code));
                    
Drop table if exists Trade cascade;
Create table Trade (TimeStamp TIMESTAMP,
                    Quantity NUMBER,
                    Price NUMBER,
                    OrderId Number,
                    FOREIGN KEY (OrderId) REFERENCES Orderr(Id)) ;

INSERT INTO Trader (Code, Name)
VALUES ('JDO', 'John Doe');

INSERT INTO Trader (Code, Name) VALUES ('JSM', 'John Smith');

Insert into Orderr (Ticker, Trader) VALUES ('PETR4', 'JDO');
Insert into Orderr (Ticker, Trader) VALUES ('ITUB4', 'JSM');

Insert into Trade Values (CURRENT_TIMESTAMP, 1000, 25.123456, 1);
Insert into Trade Values (CURRENT_TIMESTAMP, 2000, 40.0, 2);